version: '1.0.{build}'

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:
  NODE_ENV: production
  GH_TOKEN:
    secure: X1ipv8Xm+HOYvBHWKjnhmcuZJyZaRmcUUHvoilodOz89blOng+m0iC48wcBwTVGgVeyQPBH1lg3h1PHjkF1aLQ==

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 5 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm prune
  - npm update

before_build:
  - cmd: SET PATH=%cd%\node_modules\.bin\;%PATH%

build_script:
  - node --version
  - npm --version
  - echo ">>>>>>ls" && ls
  - echo ">>>>>>ls node_modules" && ls node_modules
  - echo ">>>>>>ls node_modules\.bin" && ls node_modules\.bin
  - npm run dist

test: off
